### PR TITLE
fix: Bug 1936394 - Remove support for search-config v1 and sort ordering, improve loading speed

### PR DESCRIPTION
**Pull request by Standard8**
This drops v1 support, and in the process fixes the "Region/locale by engine" view and sort ordering on the main view.

I've also included some fixes for improving the loading time of the page, by reducing the necessary queries on remote settings, and making the remaining ones to happen in parallel.

### CODE REVIEW

**Comment by Standard8** [comment]
Note, this will need rebasing once #222 has been reviewed & landed.

**Review by mandysGit — CHANGES_REQUESTED** [review]
The Compare Configurations page isn't working. I've compared main to this branch and this branch isn't doesn't load any engines for `Changed engines` section. 

**Steps to reproduce the problem:**

1. Go to Compare Configurations
2. For Primary Config, click Production
3. For Compare With, click Manual Entry
4. Remove a property from any engine. For example, I remove `"base": "https://dict.longdo.com/"`

**Actual:** 
No engines listed

**Expected:** 
longdo

**Comment by mandysGit** [comment]
Question: 
I thought the main view was sorting properly. I'm not sure how to spot the difference. 

Could you give me a bit more detail regarding: what is the issue with the sort ordering? And what were the properties you set to see the ordering is off?

**Comment by Standard8** [comment]
> > The Compare Configurations page isn't working. I've compared main to this branch and this branch isn't doesn't load any engines for `Changed engines` section.
> 
> This does appear to be wrong, it looks like we're not using the modified configuration, but reloading it. I'll investigate.

I've just fixed it, I also fixed notifying about errors in the manual configuration when on the compare config view.

**Comment by mandysGit** [comment]
Thank you. It looks good 👍🏼

**Review by mandysGit — APPROVED** [review]

**Pull request merged**
